### ISSUE TITLE
gulp/lodash swallow properties named "should"

### ISSUE THREAD

**Issue by deniaz** [unic/estatico#24] opened 2016-12-02 06:42 UTC
**Gulp Task**

```javascript
'use strict';

const gulp = require('gulp'),
  _ = require('lodash');

const taskName = 'react';

gulp.task(taskName, () => {
  const obj = {};

  const wtf = {
    "inside": {
      "can": ['can', 'can'],
      "should": ['should', 'should']
    }
  };

  console.info(`===== ${_.VERSION} =====`);
  console.log(_.merge(obj, wtf));
});

module.exports = {
  taskName,
};
```

**Expected Output**
```
===== 4.16.4 =====
{ inside: { can: [ 'can', 'can' ], should: [ 'should', 'should' ] } }
```

**Actual Output**
```
===== 4.16.4 =====
{ inside: { can: [ 'can', 'can' ] } }
```

If you run the same code in the browser / in a clean JS file with node, it'll work as expected. Also, this only happens with `should` as far as I can tell. I'm not even sure where the bug lies.

If I can ever figure it out I'll open a Pull Request.

**Comment by tschuems** [comment] 2016-12-02 12:57
i just tried to reproduce this.

it works fine on my client.

**Output**

```
===== 4.16.4 =====
{ inside: { can: [ 'can', 'can' ], should: [ 'should', 'should' ] } }
```

anyone else can reproduce this failure?

**Comment by backflip** [comment] 2017-01-25 19:38
I cannot reproduce it either. Which Node version are you running it on, @deniaz?

**Comment by orioltf** [comment] 2017-01-25 22:03
I've run your example script withseveral random lodash versions in our current .nvm environment without issues so far. So my question to @deniaz would be the same.

**Comment by orioltf** [comment] 2017-05-09 10:02
Without further feedback I close this issue.

**Closed as completed by orioltf** 2017-05-09 10:02 UTC
